---
- name: Configure Swarm, and Join Workers
  hosts: all
  remote_user: ec2-user
  become: yes
  roles:
  - { role: RedHat_common, when: ansible_os_family == 'RedHat' }
  # - docker

# - name: Configure Manager
#   hosts: swarm_manager
#   remote_user: ec2-user
#   become: yes
#   when: ansible_facts['os_family'] == "RedHat"
#   roles:
#   - RedHat_common
#   # - docker